version: '3'

services:
  reactjs-client:
    image: reactjs-client
    stdin_open: true
    container_name: reactjs-client
    ports:
      - 5000:3000
    build:
      context: client/
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - ./client/.env.local:/app/.env.local

  nestjs-server:
    image: nestjs-server
    stdin_open: true
    container_name: nestjs-server
    ports:
      - 3000:3000
    build:
      context: server/
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      - ./server/.env:/app/.env
    depends_on:
      - mongo_db
    links:
      - mongo_db:db.local
  
  mongo_db:
    image: mongo:4.2.7
    container_name: mongo_test_db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root_pw
      - MONGO_INITDB_DATABASE=nest-test
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
